$m2 = "c:\Users\Challenge\.m2\repository"
$cp = "c:\Users\Challenge\Desktop\XClaw20260429\claw-server\target\classes"

$jars = @(
    "$m2\org\springframework\boot\spring-boot\3.2.5\spring-boot-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-autoconfigure\3.2.5\spring-boot-autoconfigure-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter\3.2.5\spring-boot-starter-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-web\3.2.5\spring-boot-starter-web-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-json\3.2.5\spring-boot-starter-json-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-tomcat\3.2.5\spring-boot-starter-tomcat-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-security\3.2.5\spring-boot-starter-security-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-validation\3.2.5\spring-boot-starter-validation-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-websocket\3.2.5\spring-boot-starter-websocket-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-aop\3.2.5\spring-boot-starter-aop-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-logging\3.2.5\spring-boot-starter-logging-3.2.5.jar",
    "$m2\org\springframework\boot\spring-boot-starter-jdbc\3.2.5\spring-boot-starter-jdbc-3.2.5.jar",
    "$m2\org\springframework\spring-core\6.1.6\spring-core-6.1.6.jar",
    "$m2\org\springframework\spring-context\6.1.6\spring-context-6.1.6.jar",
    "$m2\org\springframework\spring-beans\6.1.6\spring-beans-6.1.6.jar",
    "$m2\org\springframework\spring-aop\6.1.6\spring-aop-6.1.6.jar",
    "$m2\org\springframework\spring-expression\6.1.6\spring-expression-6.1.6.jar",
    "$m2\org\springframework\spring-web\6.1.6\spring-web-6.1.6.jar",
    "$m2\org\springframework\spring-webmvc\6.1.6\spring-webmvc-6.1.6.jar",
    "$m2\org\springframework\spring-messaging\6.1.6\spring-messaging-6.1.6.jar",
    "$m2\org\springframework\spring-websocket\6.1.6\spring-websocket-6.1.6.jar",
    "$m2\org\springframework\spring-jcl\6.1.6\spring-jcl-6.1.6.jar",
    "$m2\org\springframework\spring-jdbc\6.1.6\spring-jdbc-6.1.6.jar",
    "$m2\org\springframework\spring-tx\6.1.6\spring-tx-6.1.6.jar",
    "$m2\org\springframework\security\spring-security-core\6.2.4\spring-security-core-6.2.4.jar",
    "$m2\org\springframework\security\spring-security-web\6.2.4\spring-security-web-6.2.4.jar",
    "$m2\org\springframework\security\spring-security-config\6.2.4\spring-security-config-6.2.4.jar",
    "$m2\org\springframework\security\spring-security-crypto\6.2.4\spring-security-crypto-6.2.4.jar",
    "$m2\com\fasterxml\jackson\core\jackson-databind\2.15.4\jackson-databind-2.15.4.jar",
    "$m2\com\fasterxml\jackson\core\jackson-core\2.15.4\jackson-core-2.15.4.jar",
    "$m2\com\fasterxml\jackson\core\jackson-annotations\2.15.4\jackson-annotations-2.15.4.jar",
    "$m2\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.15.4\jackson-datatype-jsr310-2.15.4.jar",
    "$m2\com\fasterxml\jackson\dataformat\jackson-dataformat-csv\2.15.4\jackson-dataformat-csv-2.15.4.jar",
    "$m2\com\fasterxml\jackson\module\jackson-module-parameter-names\2.15.4\jackson-module-parameter-names-2.15.4.jar",
    "$m2\org\apache\tomcat\embed\tomcat-embed-core\10.1.20\tomcat-embed-core-10.1.20.jar",
    "$m2\org\apache\tomcat\embed\tomcat-embed-el\10.1.20\tomcat-embed-el-10.1.20.jar",
    "$m2\org\apache\tomcat\embed\tomcat-embed-websocket\10.1.20\tomcat-embed-websocket-10.1.20.jar",
    "$m2\jakarta\servlet\jakarta.servlet-api\6.0.0\jakarta.servlet-api-6.0.0.jar",
    "$m2\jakarta\validation\jakarta.validation-api\3.0.2\jakarta.validation-api-3.0.2.jar",
    "$m2\jakarta\annotation\jakarta.annotation-api\2.1.1\jakarta.annotation-api-2.1.1.jar",
    "$m2\jakarta\persistence\jakarta.persistence-api\3.1.0\jakarta.persistence-api-3.1.0.jar",
    "$m2\jakarta\xml\bind\jakarta.xml.bind-api\4.0.2\jakarta.xml.bind-api-4.0.2.jar",
    "$m2\org\hibernate\validator\hibernate-validator\8.0.1.Final\hibernate-validator-8.0.1.Final.jar",
    "$m2\com\baomidou\mybatis-plus-spring-boot3-starter\3.5.5\mybatis-plus-spring-boot3-starter-3.5.5.jar",
    "$m2\com\baomidou\mybatis-plus-core\3.5.5\mybatis-plus-core-3.5.5.jar",
    "$m2\com\baomidou\mybatis-plus-extension\3.5.5\mybatis-plus-extension-3.5.5.jar",
    "$m2\com\alibaba\druid-spring-boot-3-starter\1.2.21\druid-spring-boot-3-starter-1.2.21.jar",
    "$m2\com\alibaba\druid\1.2.21\druid-1.2.21.jar",
    "$m2\com\mysql\mysql-connector-j\8.0.33\mysql-connector-j-8.0.33.jar",
    "$m2\io\jsonwebtoken\jjwt-api\0.12.5\jjwt-api-0.12.5.jar",
    "$m2\io\jsonwebtoken\jjwt-impl\0.12.5\jjwt-impl-0.12.5.jar",
    "$m2\io\jsonwebtoken\jjwt-jackson\0.12.5\jjwt-jackson-0.12.5.jar",
    "$m2\org\springdoc\springdoc-openapi-starter-webmvc-ui\2.3.0\springdoc-openapi-starter-webmvc-ui-2.3.0.jar",
    "$m2\org\springdoc\springdoc-openapi-starter-webmvc-api\2.3.0\springdoc-openapi-starter-webmvc-api-2.3.0.jar",
    "$m2\org\springdoc\springdoc-openapi-starter-common\2.3.0\springdoc-openapi-starter-common-2.3.0.jar",
    "$m2\io\swagger\core\v3\swagger-core-jakarta\2.2.19\swagger-core-jakarta-2.2.19.jar",
    "$m2\io\swagger\core\v3\swagger-models-jakarta\2.2.19\swagger-models-jakarta-2.2.19.jar",
    "$m2\org\aspectj\aspectjweaver\1.9.22\aspectjweaver-1.9.22.jar",
    "$m2\ch\qos\logback\logback-classic\1.4.14\logback-classic-1.4.14.jar",
    "$m2\ch\qos\logback\logback-core\1.4.14\logback-core-1.4.14.jar",
    "$m2\org\slf4j\slf4j-api\2.0.13\slf4j-api-2.0.13.jar",
    "$m2\org\slf4j\jul-to-slf4j\2.0.13\jul-to-slf4j-2.0.13.jar",
    "$m2\org\yaml\snakeyaml\2.2\snakeyaml-2.2.jar",
    "$m2\com\fasterxml\classmate\1.6.0\classmate-1.6.0.jar",
    "$m2\org\jboss\logging\jboss-logging\3.5.3.Final\jboss-logging-3.5.3.Final.jar",
    "$m2\io\micrometer\micrometer-observation\1.12.5\micrometer-observation-1.12.5.jar",
    "$m2\io\micrometer\micrometer-commons\1.12.5\micrometer-commons-1.12.5.jar",
    "$m2\org\glassfish\jaxb\jaxb-runtime\4.0.6\jaxb-runtime-4.0.6.jar",
    "$m2\com\zaxxer\HikariCP\5.0.1\HikariCP-5.0.1.jar",
    "$m2\org\webjars\webjars-locator-lite\1.1.2\webjars-locator-lite-1.1.2.jar",
    "$m2\org\webjars\swagger-ui\5.10.3\swagger-ui-5.10.3.jar"
)

$missing = @()
foreach ($j in $jars) { if (!(Test-Path $j)) { $missing += $j } }
if ($missing.Count -gt 0) { Write-Host "Missing jars:"; $missing | ForEach-Object { Write-Host "  $_" } }

$classpath = ($jars -join ";") + ";" + $cp
$classpath | Out-File -FilePath "c:\Users\Challenge\Desktop\XClaw20260429\claw-server\classpath.txt" -Encoding UTF8 -NoNewline
Write-Host "Classpath: $($jars.Count) jars, $($missing.Count) missing"
